-- ====================================================================
-- ARCHIVO: fase_avanzada_proyecto.sql
-- ASIGNATURA: Bases de Datos Avanzadas
-- EQUIPO: Brayan Cárdenas Rodríguez (y tus compañeros de grupo)
-- SESIONES: 9 (ACID) + 10 (Concurrencia) + 11 (PL/SQL) + 12 (Seguridad)
-- ====================================================================

-- ====================================================================
-- BLOQUE 0: LIMPIEZA SEGURA (Hijos antes que padres)
-- ====================================================================
BEGIN EXECUTE IMMEDIATE 'DROP VIEW vista_gerencial_reporte'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW vista_tecnico_panel';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW vista_cliente_catalogo';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE detalles_mantenimiento CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE inventario_celulares CASCADE CONSTRAINTS';  EXCEPTION COMPONENT WHEN OTHERS THEN NULL; END;
/
PURGE RECYCLEBIN;

-- ====================================================================
-- BLOQUE 1: FASE DDL Y DATOS DE PRUEBA (Sesión 9)
-- ====================================================================
CREATE TABLE inventario_celulares (
    celular_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo       VARCHAR2(100) NOT NULL,
    stock        NUMBER        NOT NULL,
    precio       NUMBER(10,2)  NOT NULL,
    costo_interno NUMBER(10,2),
    CONSTRAINT chk_stock_no_negativo CHECK (stock >= 0)
);

CREATE TABLE detalles_mantenimiento (
    servicio_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    celular_id       NUMBER,
    tecnico          VARCHAR2(100) NOT NULL,
    repuestos_usados NUMBER DEFAULT 0,
    fecha_servicio   DATE DEFAULT SYSDATE,
    costo_repuestos  NUMBER(10,2),
    CONSTRAINT fk_celular_servicio FOREIGN KEY (celular_id) REFERENCES inventario_celulares(celular_id)
);

INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno) VALUES ('iPhone 15 Pro Max', 4, 5500000, 3800000);
INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno) VALUES ('Samsung Galaxy S24 Ultra', 3, 4800000, 3200000);
INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno) VALUES ('Xiaomi 14 Ultra', 6, 3200000, 1900000);
INSERT INTO detalles_mantenimiento (celular_id, tecnico, repuestos_usados, costo_repuestos) VALUES (1, 'Tecnico Carlos', 1, 85000);
INSERT INTO detalles_mantenimiento (celular_id, tecnico, repuestos_usados, costo_repuestos) VALUES (2, 'Tecnico Maria', 0, 0);
COMMIT;

-- ====================================================================
-- BLOQUE 2: FASE ACID Y CONCURRENCIA (Sesión 10)
-- ====================================================================
-- (Aquí pegas tus bloques DECLARE...BEGIN de escenarios de bloqueo pesimista pesados con FOR UPDATE)

-- ====================================================================
-- BLOQUE 3: AUTOMATIZACIÓN PL/SQL (Sesión 11)
-- ====================================================================
-- (Aquí incluyes el código de tu Trigger "trg_procesar_mantenimiento" y el Stored Procedure junto con sus ejecuciones de prueba)

-- ====================================================================
-- BLOQUE 4: CAPA DE SEGURIDAD DCL (Sesión 12 - Código Completo de la Sección 5 de la Guía)
-- ====================================================================
CREATE OR REPLACE VIEW vista_cliente_catalogo AS
SELECT celular_id, modelo, precio AS precio_venta,
       CASE WHEN stock = 0 THEN 'Agotado' WHEN stock <= 2 THEN 'Ultimas unidades' ELSE 'En stock' END AS disponibilidad
FROM inventario_celulares WHERE stock >= 0;
/

CREATE OR REPLACE VIEW vista_tecnico_panel AS
SELECT ic.celular_id, ic.modelo, ic.stock AS repuestos_disponibles, dm.servicio_id, dm.tecnico, dm.repuestos_usados, dm.fecha_servicio, dm.costo_repuestos
FROM inventario_celulares ic LEFT JOIN detalles_mantenimiento dm ON ic.celular_id = dm.celular_id
ORDER BY dm.fecha_servicio DESC NULLS LAST;
/

CREATE OR REPLACE VIEW vista_gerencial_reporte AS
SELECT ic.modelo, ic.stock AS stock_actual, ic.precio AS precio_venta, ic.costo_interno,
       ROUND(((ic.precio - ic.costo_interno) / ic.precio) * 100, 1) AS margen_pct,
       COUNT(dm.servicio_id) AS total_servicios, NVL(SUM(dm.repuestos_usados), 0) AS repuestos_consumidos, NVL(SUM(dm.costo_repuestos), 0) AS gasto_repuestos,
       CASE WHEN ic.stock = 0 THEN 'CRITICO: Sin stock' WHEN ic.stock <= 2 THEN 'ALERTA: Stock bajo' ELSE 'Normal' END AS estado_inventory
FROM inventario_celulares ic LEFT JOIN detalles_mantenimiento dm ON ic.celular_id = dm.celular_id
GROUP BY ic.celular_id, ic.modelo, ic.stock, ic.precio, ic.costo_interno
ORDER BY ic.stock ASC;
/

-- SCRIPT DE ROLES SIMULADOS (Comentados por restricción de Live SQL)
-- CREATE ROLE rol_tecnico_vendedor;
-- GRANT SELECT ON vista_cliente_catalogo TO rol_tecnico_vendedor;
-- GRANT SELECT ON vista_tecnico_panel TO rol_tecnico_vendedor;
-- GRANT INSERT ON detalles_mantenimiento TO rol_tecnico_vendedor;

-- PRUEBAS DE SEGURIDAD OPERACIONALES
SELECT 'Prueba 1' AS test, modelo, precio_venta FROM vista_cliente_catalogo;

-- ====================================================================
-- BLOQUE 5: VERIFICACIÓN DICCIONARIO
-- ====================================================================
SELECT object_name, object_type, status FROM user_objects WHERE object_type IN ('TABLE','TRIGGER','PROCEDURE','VIEW') ORDER BY object_type, object_name;