-- ============================================================
-- TALLER-PARCIAL  -  BASES DE DATOS AVANZADAS
-- Adaptacion al proyecto: OPTICA
-- (clientes . optometras . pacientes . examenes visuales)
--
-- Ejecutar COMPLETO con Run (triangulo verde) en
-- Oracle Live SQL / Free SQL Worksheet.
-- El script es idempotente: se puede correr varias veces.
-- ============================================================

SET SERVEROUTPUT ON;

-- ============================================================
-- SCRIPT DE INICIO  -  Limpieza + tablas base + datos de prueba
-- ============================================================

-- PASO 1: Limpiar objetos de sesiones anteriores (sin error si no existen)
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_historial_examen';                    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_optometra_unico_dia';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE articulos_examen CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE examenes CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE pacientes CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE optometras CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE clientes CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE t_examen FORCE';                        EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PASO 2: Clientes (titulares de la cuenta en la optica)
CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100) NOT NULL,
    telefono   VARCHAR2(15),
    email      VARCHAR2(100)
);

-- PASO 3: Optometras (profesionales que realizan el examen visual)
CREATE TABLE optometras (
    optometra_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(60),
    tarifa_min   NUMBER(8,2) NOT NULL,   -- precio por minuto de consulta
    CHECK (tarifa_min > 0)
);

-- PASO 4: Pacientes (personas examinadas; un cliente puede traer a su familia)
CREATE TABLE pacientes (
    paciente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  NUMBER NOT NULL,
    nombre      VARCHAR2(60) NOT NULL,
    parentesco  VARCHAR2(40) NOT NULL,   -- Titular, Hijo/a, Conyuge...
    edad        NUMBER,
    CONSTRAINT fk_paciente_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id),
    CONSTRAINT chk_edad CHECK (edad > 0)
);

-- PASO 5: Examenes (cada examen lo realiza un optometra a un paciente)
-- La columna objeto datos_examen se agrega en el Ejercicio 3 con ALTER TABLE.
CREATE TABLE examenes (
    examen_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id  NUMBER NOT NULL,
    optometra_id NUMBER NOT NULL,
    fecha        DATE DEFAULT SYSDATE,
    diagnostico  VARCHAR2(300),
    CONSTRAINT fk_examen_paciente FOREIGN KEY (paciente_id)
        REFERENCES pacientes(paciente_id),
    CONSTRAINT fk_examen_optometra FOREIGN KEY (optometra_id)
        REFERENCES optometras(optometra_id)
);

-- PASO 6: Datos de prueba - clientes
INSERT INTO clientes (nombre, telefono, email) VALUES ('Sofia Gutierrez', '3001234567', 'sofia@mail.com');
INSERT INTO clientes (nombre, telefono, email) VALUES ('Carlos Restrepo', '3117654321', 'carlos@mail.com');

-- PASO 7: Datos de prueba - optometras
INSERT INTO optometras (nombre, especialidad, tarifa_min) VALUES ('Dra. Laura Ospina', 'Optometria Pediatrica', 8500);
INSERT INTO optometras (nombre, especialidad, tarifa_min) VALUES ('Dr. Miguel Torres', 'Contactologia', 5000);

-- PASO 8: Datos de prueba - pacientes
INSERT INTO pacientes (cliente_id, nombre, parentesco, edad) VALUES (1, 'Sofia Gutierrez', 'Titular', 34);
INSERT INTO pacientes (cliente_id, nombre, parentesco, edad) VALUES (1, 'Mateo Gutierrez', 'Hijo',    8);
INSERT INTO pacientes (cliente_id, nombre, parentesco, edad) VALUES (2, 'Carlos Restrepo', 'Titular', 45);
COMMIT;

-- PASO 9: Verificacion
SELECT 'clientes'   AS tabla, COUNT(*) AS filas FROM clientes   UNION ALL
SELECT 'optometras',          COUNT(*)          FROM optometras UNION ALL
SELECT 'pacientes',           COUNT(*)          FROM pacientes;
-- Resultado esperado: clientes=2, optometras=2, pacientes=3


-- ============================================================
-- EJERCICIO 1 (20 pts) - DDL
-- Tabla de articulos vendidos/recetados en cada examen, con integridad.
-- Equivale a medicamentos_consulta del taller original.
-- ============================================================
CREATE TABLE articulos_examen (
    articulo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id   NUMBER NOT NULL,
    articulo    VARCHAR2(100) NOT NULL,    -- ej: 'Lente antirreflejo', 'Montura'
    cantidad    NUMBER NOT NULL,
    costo_unit  NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_articulo_examen FOREIGN KEY (examen_id)
        REFERENCES examenes(examen_id),
    CONSTRAINT chk_cantidad   CHECK (cantidad > 0),
    CONSTRAINT chk_costo_unit CHECK (costo_unit > 0)
);


-- ============================================================
-- EJERCICIO 2 (20 pts) - DML
-- La Dra. Laura Ospina (1) atendio a Sofia (paciente 1) y a Carlos (paciente 3).
-- El Dr. Miguel Torres (2) atendio a Mateo (paciente 2).
-- ============================================================

-- Parte A: insertar los tres examenes
INSERT INTO examenes (paciente_id, optometra_id, diagnostico)
VALUES (1, 1, 'Control anual de vision');
INSERT INTO examenes (paciente_id, optometra_id, diagnostico)
VALUES (3, 1, 'Revision por fatiga visual');
INSERT INTO examenes (paciente_id, optometra_id, diagnostico)
VALUES (2, 2, 'Tamizaje visual preventivo');
COMMIT;

-- Demo opcional del Ej1: articulos vendidos en el examen 1
INSERT INTO articulos_examen (examen_id, articulo, cantidad, costo_unit)
VALUES (1, 'Lente antirreflejo CR-39', 2, 95000);
INSERT INTO articulos_examen (examen_id, articulo, cantidad, costo_unit)
VALUES (1, 'Montura acetato', 1, 180000);
COMMIT;

-- Parte B: verificacion con JOIN (nombre del paciente + nombre del optometra)
SELECT p.nombre AS paciente,
       o.nombre AS optometra,
       e.diagnostico,
       e.fecha
FROM   examenes  e
JOIN   pacientes  p ON e.paciente_id  = p.paciente_id
JOIN   optometras o ON e.optometra_id = o.optometra_id
ORDER  BY e.examen_id;


-- ============================================================
-- EJERCICIO 3 (25 pts) - CREATE TYPE
-- Tipo t_examen que encapsula la atencion y calcula el honorario
-- DENTRO de la base de datos (no en la aplicacion).
-- ============================================================

-- Especificacion del tipo
CREATE OR REPLACE TYPE t_examen AS OBJECT (
    optometra    VARCHAR2(100),
    duracion_min NUMBER,
    tarifa_min   NUMBER(8,2),
    es_urgencia  NUMBER,            -- 1 = urgencia, 0 = normal
    MEMBER FUNCTION calcular_honorario RETURN NUMBER
);
/

-- Cuerpo del tipo
CREATE OR REPLACE TYPE BODY t_examen AS
    MEMBER FUNCTION calcular_honorario RETURN NUMBER IS
        v_base NUMBER;
    BEGIN
        v_base := SELF.duracion_min * SELF.tarifa_min;
        IF SELF.es_urgencia = 1 THEN
            RETURN v_base * 1.50;     -- recargo de urgencia del 50%
        ELSE
            RETURN v_base;
        END IF;
    END;
END;
/

-- Agregar la columna objeto a la tabla examenes
ALTER TABLE examenes ADD datos_examen t_examen;

-- Insertar un examen completo usando el constructor del tipo
-- (urgencia de 30 min con la Dra. Laura, tarifa 8500/min)
INSERT INTO examenes (paciente_id, optometra_id, diagnostico, datos_examen)
VALUES (1, 1, 'Urgencia: cuerpo extrano en el ojo',
        t_examen('Dra. Laura Ospina', 30, 8500, 1));
COMMIT;

-- Invocar el metodo (el alias de tabla 'e' es OBLIGATORIO)
SELECT e.examen_id,
       e.datos_examen.optometra            AS optometra,
       e.datos_examen.calcular_honorario() AS honorario
FROM   examenes e
WHERE  e.datos_examen IS NOT NULL;
-- Esperado: 30 * 8500 * 1.50 = 382500


-- ============================================================
-- EJERCICIO 4 (15 pts) - ACID y Concurrencia: FOR UPDATE NOWAIT
-- Bloquea la fila del optometra para que dos recepcionistas no
-- lo asignen al mismo tiempo. Captura ORA-00054 (recurso ocupado).
-- ============================================================
DECLARE
    v_nombre  VARCHAR2(100);
    v_tarifa  NUMBER(8,2);
    e_ocupado EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_ocupado, -54);   -- ORA-00054
BEGIN
    SELECT nombre, tarifa_min
    INTO   v_nombre, v_tarifa
    FROM   optometras
    WHERE  optometra_id = 1
    FOR UPDATE NOWAIT;

    DBMS_OUTPUT.PUT_LINE('Optometra: ' || v_nombre || ' | Tarifa/min: ' || v_tarifa);
    COMMIT;
EXCEPTION
    WHEN e_ocupado THEN
        DBMS_OUTPUT.PUT_LINE('Optometra ocupado. Intenta en un momento.');
END;
/


-- ============================================================
-- EJERCICIO 5 (10 pts) - Trigger BEFORE INSERT
-- Impide que un mismo optometra tenga dos examenes el mismo dia.
-- ============================================================
CREATE OR REPLACE TRIGGER trg_optometra_unico_dia
    BEFORE INSERT ON examenes
    FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   v_count
    FROM   examenes
    WHERE  optometra_id = :NEW.optometra_id
    AND    TRUNC(fecha) = TRUNC(:NEW.fecha);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'El optometra ya tiene un examen registrado para esta fecha.');
    END IF;
END;
/

-- Prueba del trigger. Usamos una fecha "limpia" (sin examenes previos)
-- para que el primer INSERT pase y el segundo falle por el trigger.
-- OJO: el error del segundo INSERT es el resultado ESPERADO; demuestra
-- que el trigger funciona. No es una falla del script.
INSERT INTO examenes (paciente_id, optometra_id, fecha, diagnostico)
VALUES (1, 1, DATE '2025-07-10', 'Prueba trigger - primero');   -- OK

INSERT INTO examenes (paciente_id, optometra_id, fecha, diagnostico)
VALUES (2, 1, DATE '2025-07-10', 'Prueba trigger - segundo');   -- DEBE FALLAR (-20001)


-- ============================================================
-- EJERCICIO 6 (10 pts) - Vista segura: historial para el cliente
-- El cliente ve el historial de sus pacientes, SIN tarifas ni costos
-- internos de la optica (informacion financiera).
-- ============================================================
CREATE OR REPLACE VIEW v_historial_examen AS
SELECT p.nombre       AS paciente,
       p.parentesco,
       c.nombre       AS cliente,
       o.nombre       AS optometra,
       o.especialidad,
       e.diagnostico,
       e.fecha
FROM   examenes  e
JOIN   pacientes  p ON e.paciente_id  = p.paciente_id
JOIN   clientes   c ON p.cliente_id   = c.cliente_id
JOIN   optometras o ON e.optometra_id = o.optometra_id;

-- Historial visible para Sofia Gutierrez (cliente_id = 1)
SELECT *
FROM   v_historial_examen
WHERE  cliente = 'Sofia Gutierrez';

-- ============================================================
-- FIN DEL TALLER
-- ============================================================
